version: "3.7"

services:
  uwsgi:
    build: ./myapp
    container_name: uwsgi
    restart: always
    expose:
      - 8080
    volumes:
      - ./templates:/templates
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./templates:/templates
